### PR TITLE
Add unit testing with pytest

### PR DESCRIPTION
**Pull request by anthonyprinaldi**
Add unit testing for the ace workflow interface file. 95 tests total.

### CODE REVIEW

**Comment by anthonyprinaldi** [comment]
Some files are deleted for cleanup. The main change is the addition of `test_ace_interface.py` and its config file.

**Comment by anthonyprinaldi** [comment]
The strange number of commits has to do with the (incorrect) way that I merged newer changes into my local branches

**Comment by jono3030** [comment]
Yeah re number of commits we should think about a rebase/squash strategy for our history before opening a PR into `dev`.

**Review by jono3030 — APPROVED** [review]
Looks good. Great work implementing the first unit tests for MIRACL! I'm sure this will set a precedent...

Note: let's get together at some point to think about commit strategies as well.

**Pull request merged**
